{
 "title": "KILKIS....LARISA",
 "description": "s3 ",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "temperature",
   "type": "timeseries",
   "description": "LAXANA ",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\")\nFROM \"temperature\"\nWHERE $timeFilter\nGROUP BY time(5m), \"greenhouse_id\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "humidity\"",
   "type": "timeseries",
   "description": "MAROYLIA ",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "alias": "humidity\"  MAROYLIA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") \nFROM \"humidity\" \nWHERE $timeFilter \nGROUP BY time(5m), \"greenhouse_id\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "light_intensity\" ",
   "type": "timeseries",
   "description": "NTOMATES ",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") \nFROM \"light_intensity\" \nWHERE $timeFilter \nGROUP BY time(5m), \"greenhouse_id\"\n"
    }
   ]
  }
 ]
}